name       : zathura
version    : 0.3.6
release    : 2
source     :
    - https://pwmt.org/projects/zathura/download/zathura-0.3.6.tar.gz : 086a8be25d538fc6539fbee8f01ecf16d25819dfaad50cd2dbd84e30152ccb3b
    - https://pwmt.org/projects/zathura-pdf-poppler/download/zathura-pdf-poppler-0.2.6.tar.gz : d1eb0c7a4f647c141192a2d7bf66413b9c5f1842463947ab87a8a1edcf8e58d5
    - https://pwmt.org/projects/zathura-djvu/download/zathura-djvu-0.2.5.tar.gz : 08b7110af13e17a9d221bd7a0f7d3b479b3e31631d78bc6c5efb46271a299c0d
    - https://pwmt.org/projects/zathura-cb/download/zathura-cb-0.1.5.tar.gz : 375f6912bd79648603bad51c3635ce28eaca7bf4df521c00ff9673d9b4ff6afd
    - https://pwmt.org/projects/zathura-ps/download/zathura-ps-0.2.3.tar.gz : a9eef74b12aec87ac2c4309f12d0f9c83b228fe64a788ee46b2c3a7c91779aa3
license    : BSD-3-Clause
component  : office
summary    : zathura is a highly customizable and functional document viewer based
    on the girara user interface library and several document libraries
description: |
    zathura is a highly customizable and functional document viewer based on the girara user interface library and several document libraries
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(girara-gtk3)
    - pkgconfig(libarchive)
    - pkgconfig(libspectre)
    - pkgconfig(poppler)
    - pkgconfig(sqlite3)
    - intltool
build      : |
    %make
    %make_install

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$installdir/usr/lib/pkgconfig
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
    for plugin in cb-0.1.5 djvu-0.2.5 pdf-poppler-0.2.6 ps-0.2.3; do
        tar xvf $sources/zathura-${plugin}.tar.gz
        pushd "zathura-${plugin}"
        CFLAGS="$CFLAGS -I${installdir}/usr/include" %make
        popd
    done
    popd
install    : |
    pushd plugin_build
    for plugin in cb-0.1.5 djvu-0.2.5 pdf-poppler-0.2.6 ps-0.2.3; do
        pushd "zathura-${plugin}"
        %make_install
        popd
    done
    popd
