name       : zathura
version    : 0.4.5
release    : 13
source     :
    - https://github.com/pwmt/zathura/archive/0.4.5.tar.gz : 317882fc4e05104591c011c237b2ba6bf0b3978c189f5cdf3c978cb333ee04fe
    - https://github.com/pwmt/zathura-pdf-poppler/archive/0.3.0.tar.gz : 2034f70a936d458ddc9276f769e77ff308ba3bb1b7a7cdc87bab8b9ef7ade84a
    - https://github.com/pwmt/zathura-djvu/archive/0.2.9.tar.gz : 84fae6da42e7cdc2e49ed4cd4f0315ac09716e95358b9c7487803a2cff47dbca
    - https://github.com/pwmt/zathura-cb/archive/0.1.8.tar.gz : 67206011fc375cd2f3d0bc0d7a36b182c10eb3c41961963910992393c34aa5d5
    - https://github.com/pwmt/zathura-ps/archive/0.2.6.tar.gz : 08c1927bfb8a40e201fa3638f9523d4b6d70e3444ef070bd4aa8a869b6574567
homepage   : https://pwmt.org/projects/zathura/
license    : Zlib
component  : office.viewers
summary    : zathura is a highly customizable and functional document viewer
description: |
    zathura is a highly customizable and functional document viewer based on the girara user interface library and several document libraries
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(girara-gtk3)
    - pkgconfig(libarchive)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libspectre)
    - pkgconfig(poppler)
    - pkgconfig(sqlite3)
    - pkgconfig(synctex)
    - intltool
    - python-sphinx
setup      : |
    %meson_configure
build      : |
    %ninja_build -j1
install    : |
    %ninja_install

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$installdir/%libdir%/pkgconfig
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
        for plugin in 0.1.8 0.2.6 0.2.9 0.3.0; do
            tar xvf $sources/${plugin}.tar.gz
            pushd zathura-*-$plugin
            CFLAGS="$CFLAGS -I${installdir}/usr/include" %meson_configure
            %ninja_build
            %ninja_install
            popd
        done
    popd

    # due to a limitation in the SC
    rm -v $installdir/usr/share/metainfo/org.pwmt.zathura-*.metainfo.xml
