name       : zathura
version    : 0.4.3
release    : 11
source     :
    - https://github.com/pwmt/zathura/archive/0.4.3.tar.gz : 4be4233335c1e8be009c70fa5b5a8ecd5a651fc742d1574b37d6266dc1e20dad
    - https://github.com/pwmt/zathura-pdf-poppler/archive/0.2.9.tar.gz : 34c5eb25f56cd01a3302d4bc8eb0b23e026e065d017405f3f2a30a02b9cd2530
    - https://github.com/pwmt/zathura-djvu/archive/0.2.8.tar.gz : 58325958b5aecc4f7cd8281b564aadeea151fafd1de84e4fa269932f96a3a776
    - https://github.com/pwmt/zathura-cb/archive/0.1.8.tar.gz : 67206011fc375cd2f3d0bc0d7a36b182c10eb3c41961963910992393c34aa5d5
    - https://github.com/pwmt/zathura-ps/archive/0.2.6.tar.gz : 08c1927bfb8a40e201fa3638f9523d4b6d70e3444ef070bd4aa8a869b6574567
license    : BSD-3-Clause
component  : office.viewers
summary    : zathura is a highly customizable and functional document viewer
description: |
    zathura is a highly customizable and functional document viewer based on the girara user interface library and several document libraries
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(girara-gtk3)
    - pkgconfig(libarchive)
    - pkgconfig(libspectre)
    - pkgconfig(poppler)
    - pkgconfig(sqlite3)
    - pkgconfig(synctex)
    - intltool
    - python-sphinx
setup      : |
    %meson_configure
build      : |
    %ninja_build -j1
install    : |
    %ninja_install

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$installdir/%libdir%/pkgconfig
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
        for plugin in 0.1.8 0.2.8 0.2.9 0.2.6; do
            tar xvf $sources/${plugin}.tar.gz
            pushd zathura-*-$plugin
            CFLAGS="$CFLAGS -I${installdir}/usr/include" %meson_configure
            %ninja_build
            %ninja_install
            popd
        done
    popd

    # due to a limitation in the SC
    rm -v $installdir/usr/share/metainfo/org.pwmt.zathura-*.metainfo.xml
