name       : zathura
version    : 0.4.1
release    : 10
source     :
    - https://pwmt.org/projects/zathura/download/zathura-0.4.1.tar.xz : d6f56bf6e7e05d2e91213287c7aea21481c44521b622f9e9ec06a886f51dd9fe
    - https://pwmt.org/projects/zathura-pdf-poppler/download/zathura-pdf-poppler-0.2.9.tar.xz : be0806116ea6e6c95495f5e244e0d70d2551a9058e5574b47d3e5a09bc6592dc
    - https://pwmt.org/projects/zathura-djvu/download/zathura-djvu-0.2.8.tar.xz : d0e664d5312bdc0674fdf8cc6e259c9ee1365714172bc809f9c0f69659d8b32b
    - https://pwmt.org/projects/zathura-cb/download/zathura-cb-0.1.8.tar.xz : 452a0702e257dbed6a84b7faf6b51e4eb57a163654bbcddf6301143d3770ccc4
    - https://pwmt.org/projects/zathura-ps/download/zathura-ps-0.2.6.tar.xz : 7eb085b41fc88979f997310b4e703455e6a81b6ef1ae7db0b6324b6f13c2cf73
license    : BSD-3-Clause
component  : office.viewers
summary    : zathura is a highly customizable and functional document viewer
description: |
    zathura is a highly customizable and functional document viewer based on the girara user interface library and several document libraries
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(girara-gtk3)
    - pkgconfig(libarchive)
    - pkgconfig(libspectre)
    - pkgconfig(poppler)
    - pkgconfig(sqlite3)
    - pkgconfig(synctex)
    - intltool
    - python-sphinx
setup      : |
    %meson_configure
build      : |
    %ninja_build -j1
install    : |
    %ninja_install

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$installdir/%libdir%/pkgconfig
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
        for plugin in cb-0.1.8 djvu-0.2.8 pdf-poppler-0.2.9 ps-0.2.6; do
            tar xvf $sources/zathura-${plugin}.tar.xz
            pushd "zathura-${plugin}"
            CFLAGS="$CFLAGS -I${installdir}/usr/include" %meson_configure
            %ninja_build
            %ninja_install
            popd
        done
    popd

    # due to a limitation in the SC
    rm -v $installdir/usr/share/metainfo/org.pwmt.zathura-*.metainfo.xml
