name       : zathura
version    : 0.4.7
release    : 19
source     :
    - https://github.com/pwmt/zathura/archive/0.4.7.tar.gz : dbea0d5c42bfb813640af2587edbf04a93e6e87232f429e09845e5a9d0049ffb
    - https://github.com/pwmt/zathura-pdf-poppler/archive/0.3.0.tar.gz : 2034f70a936d458ddc9276f769e77ff308ba3bb1b7a7cdc87bab8b9ef7ade84a
    - https://github.com/pwmt/zathura-djvu/archive/0.2.9.tar.gz : 84fae6da42e7cdc2e49ed4cd4f0315ac09716e95358b9c7487803a2cff47dbca
    - https://github.com/pwmt/zathura-cb/archive/0.1.8.tar.gz : 67206011fc375cd2f3d0bc0d7a36b182c10eb3c41961963910992393c34aa5d5
    - https://github.com/pwmt/zathura-ps/archive/0.2.6.tar.gz : 08c1927bfb8a40e201fa3638f9523d4b6d70e3444ef070bd4aa8a869b6574567
    - https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.5.tar.gz : 6344acda225ca637fc72788cacce7448cd2e69ac13f19429726786a0b62cd7e3
homepage   : https://pwmt.org/projects/zathura/
license    : Zlib
component  :
    - office.viewers
    - mupdf : office.viewers
    - poppler : office.viewers
summary    : zathura is a highly customizable and functional document viewer
description:
    - zathura is a highly customizable and functional document viewer based on the girara user interface library and several document libraries
    - mupdf : mupdf plugin for zathura
    - poppler : poppler plugin for zathura
patterns   :
    - mupdf :
        - /usr/lib64/zathura/libpdf-mupdf.so
        - /usr/share/applications/org.pwmt.zathura-pdf-mupdf.desktop
    - poppler :
        - /usr/lib64/zathura/libpdf-poppler.so
        - /usr/share/applications/org.pwmt.zathura-pdf-poppler.desktop
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(girara-gtk3)
    - pkgconfig(jbig2dec)
    - pkgconfig(libarchive)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libspectre)
    - pkgconfig(libturbojpeg)
    - pkgconfig(poppler)
    - pkgconfig(sqlite3)
    - pkgconfig(synctex)
    - intltool
    - mupdf-devel
    - python-sphinx
rundeps    :
    - mupdf :
        - zathura
    - poppler :
        - zathura
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$installdir/%libdir%/pkgconfig
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
        for plugin in 0.1.8 0.2.6 0.2.9 0.3.0 0.3.5; do
            tar xvf $sources/${plugin}.tar.gz
            pushd zathura-*-$plugin
            mesonflag=""
            if [ $plugin == '0.3.5' ]; then
                perl -pi -e 's/\s*mupdfthird.*$//;' -e 's/  mupdf,/  mupdf/;' meson.build
                %patch -p1 < $pkgfiles/update-zathura-mupdf-to-1.17.0.patch
                mesonflag="-Dlink-external=true"
            fi
            CFLAGS="$CFLAGS -I${installdir}/usr/include" %meson_configure $mesonflag
            %ninja_build
            %ninja_install
            popd
        done
    popd

    # due to a limitation in the SC
    rm -v $installdir/usr/share/metainfo/org.pwmt.zathura-*.metainfo.xml
