name       : zathura
version    : 0.3.7
release    : 5
source     :
    - https://pwmt.org/projects/zathura/download/zathura-0.3.7.tar.gz : 22afff89f4093f22fb82188417ff9bfa9695b19a4fe894dca05b7c821b390ff0
    - https://pwmt.org/projects/zathura-pdf-poppler/download/zathura-pdf-poppler-0.2.7.tar.gz : 985e4e4dce6143fdfd246e78b0ccbef0d32b8809c6a4f08bb53a2f7dfbd383c0
    - https://pwmt.org/projects/zathura-djvu/download/zathura-djvu-0.2.6.tar.gz : aefef6a3b702fa06145f16f2559490f4d96d3206bafd4e0c78ac184788cac05f
    - https://pwmt.org/projects/zathura-cb/download/zathura-cb-0.1.6.tar.gz : 888e95421e13b944d19604fab129e5992636f404e7ed20751d4f50546f2535ba
    - https://pwmt.org/projects/zathura-ps/download/zathura-ps-0.2.4.tar.gz : fb9fc7e9e7765fb0aa2935b93ff3663332d0d884df35e8d0b1ea7e4b1fa0abdb
license    : BSD-3-Clause
component  : office.viewers
summary    : zathura is a highly customizable and functional document viewer based
    on the girara user interface library and several document libraries
description: |
    zathura is a highly customizable and functional document viewer based on the girara user interface library and several document libraries
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(girara-gtk3)
    - pkgconfig(libarchive)
    - pkgconfig(libspectre)
    - pkgconfig(poppler)
    - pkgconfig(sqlite3)
    - intltool
build      : |
    %make
    %make_install

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$installdir/usr/lib/pkgconfig
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
    for plugin in cb-0.1.6 djvu-0.2.6 pdf-poppler-0.2.7 ps-0.2.4; do
        tar xvf $sources/zathura-${plugin}.tar.gz
        pushd "zathura-${plugin}"
        CFLAGS="$CFLAGS -I${installdir}/usr/include" %make
        popd
    done
    popd
install    : |
    pushd plugin_build
    for plugin in cb-0.1.6 djvu-0.2.6 pdf-poppler-0.2.7 ps-0.2.4; do
        pushd "zathura-${plugin}"
        %make_install
        popd
    done
    popd
